*** 
*** ReFox X  #UK933629  MANRIQUE ORELLANA  MANSOFT SYSTEMS [VFP80]
***
SET CONSOLE OFF
SET PRINTER TO COM1
SET DEVICE TO PRINTER
SET MARGIN TO 0
SET PRINTER ON
SET PRINTER OFF
RETURN
ENDPROC
**
*** 
*** ReFox - retrace your steps ... 
***
